### ISSUE TITLE
Could I merge with the organization?

### ISSUE THREAD

**Issue by luizberti** [brazilian-utils/old-python#1]
I literally wrote a Python package which is already on pip with the same name as this project 2 years ago, currently supporting CPF and CNPJ.

Could I suggest not doing (at least the python part) from scratch and merging my project with this organization?

https://github.com/luizberti/brutils

**Comment by hyanmandian** [comment]
Yes! We'll appreciate :D 

Feel free to send a PR. I think that @alexrochas can help you with that.

**Comment by luizberti** [comment]
I was actually thinking about migrating the repo into the organization, is there a way to do that?

Mine already has CPF and CNPJ support, with tests, and documentation in both english and portuguese, and runs on 2.7 and 3.x. I think it's easier to use that as a starting point than to migrate my progress into this repo which has just started.

I had actually been planning to add support for other documents for a long time, it's great to see an umbrella project come around this.

**Comment by hyanmandian** [comment]
@luizberti I added you as contributor :D any questions talk with @alexrochas, he is responsible for this project.

Welcome to brazilian-utils!
